### ISSUE TITLE
Modify Jobs_UpdateMsg to support optional Expected version field

### ISSUE THREAD

**Issue by priyamourya25** [aws/Jobs-for-AWS-IoT-embedded-sdk#100]
Please refer the description of expected version for iot jobs:
https://docs.aws.amazon.com/iot/latest/apireference/API_iot-jobs-data_UpdateJobExecution.html#API_iot-jobs-data_UpdateJobExecution_RequestSyntax

This is an optional field and the user should be allowed to not pass and still construct a payload without the field. The API forces to provide an optional field here: https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk/blob/8be356054429da35e9f45dce50404ce1d6b106fe/source/jobs.c#L844

Could you please modify the API so that it allows to append values only if they are passed by the user?

**Comment by rawalexe** [comment]
Hello Priya,
Thank you for pointing this out. Can you please make a PR with the change, we can quickly go over the changes and have it merged.

Best Regards,
AR

**Comment by kstribrnAmzn** [comment]
PR to add this feature - https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk/pull/104

**Comment by kstribrnAmzn** [comment]
PR is now merged. Closing
